version: '3.6'

services:

    edgrafana:
        image: "ganadara135/edgrafana:7.1.0-pre"
        volumes: 
                    # For production
            # - ~/grafana-plugins:/var/lib/grafana/plugins
                    # For local dev 
            - ~/work/energy/test/grafana-plugins:/var/lib/grafana/plugins
        # environment:
        #     GF_RENDERING_SERVER_URL: "http://27.96.131.183:8681/render"
        #     GF_RENDERING_CALLBACK_URL: "http://27.96.131.183:3003/"
        #     GF_LOG_FILTERS: "rendering:debug"
        environment:        # For Local
            # GF_RENDERING_SERVER_URL: "http://renderer:8681/render"
            GF_RENDERING_SERVER_URL: "http://renderer:8081/render"
            GF_RENDERING_CALLBACK_URL: "http://edgrafana:3000/"
            # GF_RENDERING_CALLBACK_URL: "http://localhost:3003/"
            GF_LOG_FILTERS: "rendering:debug"
        expose:
            - 3003
        ports:
            - "3003:3000"
        networks:
            - ednet

    renderer: 
        image: "grafana/grafana-image-renderer:latest"
        container_name: renderer
        depends_on: 
            - edgrafana
        ports: 
            - "8681:8081"
        networks:
            - ednet

    pdfreporter:
        image: izakmarais/grafana-reporter:${gr_version:-latest}
        depends_on: 
            - edgrafana
            - renderer
        command: "-ip edgrafana:3000"
        # command: "-ip localhost:3003"
        ports:
            - "8686:8686"
        networks:
            - ednet

networks:
    ednet:
        name: ednet


# curl -H "Authorization: Bearer eyJrIjoidjl2dmRpT3pyTG5nbGJxTzA3anMxY2I4bGl5WW1tZXIiLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3000/api/dashboards/home
# curl -H "Authorization: Bearer eyJrIjoiWWU5NXVUWEdIckRIbmR6SGk3VTZqbHQ1Y2ZsWm8xZEciLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3003/api/dashboards/home
# curl -H "Authorization: Bearer eyJrIjoiMW1EZkR2MEU5Y2hMZVozSVljbXgxOGNNS3k4M3Y4WjciLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3003/api/dashboards/home
# curl -H "Authorization: Bearer eyJrIjoieTF5Z0hCT0dIclE0M2NtVXBXcHJKUkFPcVFMZ3h4YlEiLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3003/api/dashboards/home
# curl -H "Authorization: Bearer eyJrIjoiUzM2YU9TeDJ6ckNRUElaaW9rc3BMdWo4SUE3NDd2cTYiLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3003/api/dashboards/home
# curl -H "Authorization: Bearer eyJrIjoiVWd3ekNoNDZzdndOSWNCNXFIakdCZTZVdDFhdVpHdDQiLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3003/api/dashboards/home
# curl -H "Authorization: Bearer eyJrIjoidmR3ZW1hOElOcUoycWowYWZzN1BlSnZsTFpyTmNXRnciLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3003/api/dashboards/home
# curl -H "Authorization: Bearer eyJrIjoiRmlMZm5qb2N4RDFwSHVNQ2hJUWxpQzRLT0JIbm9mRnYiLCJuIjoicGRmIiwiaWQiOjF9" http://localhost:3003/api/dashboards/home