version: "2"
services:

  grafana:
    image: "grafana/grafana:6.6.1"
    ports:
      - 3100:3000
    # volumes:
    #   - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"

  grafana-reporter:
    image: "ludenus/grafana-reporter:latest"
    ports:
      - 18686:8686
    entrypoint: /entrypoint.sh
    # volumes:
    #   - ./grafana-reporter/dashboard.json:/dashboard.json:ro
    environment:
      GRAFANA_HOST: "grafana"
      GRAFANA_PORT: "3000"
      GRAFANA_USER: "admin"
      GRAFANA_PASS: "admin"
      GRAFANA_REPORTER_EXTERNAL_URL: "http://localhost:18686"
    depends_on:
      - grafana
