version: "2"

services:
    edgrafana: 
        image: "ganadara135/edgrafana:7.1.0-pre"
        container_name: edgrafana
        volumes: 
                    # For production
            - ~/grafana-plugins:/var/lib/grafana/plugins
                    # For local dev 
            # - ~/work/energy/test/grafana-plugins:/var/lib/grafana/plugins
        environment: 
                    # For production
            GF_RENDERING_SERVER_URL: "http://27.96.131.183:8081/render"
            GF_RENDERING_CALLBACK_URL: "http://27.96.131.183:3003/"
                    # For local dev 
            # GF_RENDERING_SERVER_URL: "http://localhost:8081/render"
            # GF_RENDERING_CALLBACK_URL: "http://localhost:3000/"
            GF_LOG_FILTERS: "rendering:debug"
        # network_mode: host    this is not working
        ports: 
            - "3003:3000"
    renderer: 
        image: "grafana/grafana-image-renderer:latest"
        container_name: renderer
        depends_on: 
            - edgrafana
        # network_mode: host    this is not working
        ports: 
            - "8081"
            
    pdfreporter: 
        image: "izakmarais/grafana-reporter"
        container_name: pdfreporter
        depends_on: 
            - edgrafana
            - renderer
        # network_mode: host
        ports: 
            - "8086:8086"
        # command: "-ip grafana:3000"
